### ISSUE TITLE
AttributeError: 'DashboardAPI' object has no attribute 'mx_l3_firewall'

### ISSUE THREAD

**Issue by bccrew** [meraki/automation-scripts#46]
When using the export_mx_l3.py script to try to export the L3 firewall rules, the following error occurs.

user@ubuntu:~/automation-scripts# python3 export_mx_l3.py -k ********************* -n L_63106689*************
2023-05-03 07:57:36       meraki:     INFO > Meraki dashboard API session initialized with these parameters: {'version': '1.32.1', 'api_key': '****************************************', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 2, 'simulate': False, 'be_geo_id': None, 'caller': None, 'use_iterator_for_get_pages': False}
Traceback (most recent call last):
  File "/user/automation-scripts/export_mx_l3.py", line 84, in <module>
    main(sys.argv[1:])
  File "/user/automation-scripts/export_mx_l3.py", line 72, in main
    fw_rules = m.mx_l3_firewall.getNetworkL3FirewallRules(net_id)
AttributeError: 'DashboardAPI' object has no attribute 'mx_l3_firewall'

**Comment by rasmusbirkelund** [comment]
Have you updated your git repo? It looks like there was a [change](https://github.com/meraki/automation-scripts/commit/912f93f5eb68190f64f27f1bd2dd95ebec61019d) in that file commited approx. 3 months ago which addresses that specific line.

**Comment by bccrew** [comment]
> Have you updated your git repo? It looks like there was a [change](https://github.com/meraki/automation-scripts/commit/912f93f5eb68190f64f27f1bd2dd95ebec61019d) in that file commited approx. 3 months ago which addresses that specific line.

Hi

Yes, the export script works since I updated it to the latest. But the import script is still broken.

user@ubuntu:~/automation-scripts# python3 import_mx_l3.py -k ********************************* -n L_****************** -f mx_l3fw_rules__2023-05-03_12-58-40.csv
Reading file mx_l3fw_rules__2023-05-03_12-58-40.csv
{'policy': 'allow', 'protocol': 'udp', 'srcCidr': '10.0.0.1/32', 'srcPort': '80', 'destCidr': 'vpn.test.com/32', 'destPort': '443', 'comment': 'ALLOWTEST2', 'syslogEnabled': False}
{'policy': 'deny', 'protocol': 'icmp', 'srcCidr': 'VLAN(99).*/32', 'srcPort': 'Any', 'destCidr': 'OBJ(*****************)/32', 'destPort': 'Any', 'comment': 'DENYTEST1', 'syslogEnabled': True}
{'policy': 'allow', 'protocol': 'Any', 'srcCidr': 'Any', 'srcPort': 'Any', 'destCidr': 'Any', 'destPort': 'Any', 'comment': 'Default rule', 'syslogEnabled': False}
Processed all 3 rules of file mx_l3fw_rules__2023-05-03_12-58-40.csv
2023-05-04 21:14:44       meraki:     INFO > Meraki dashboard API session initialized with these parameters: {'version': '1.32.1', 'api_key': '************************************fc85', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 2, 'simulate': True, 'be_geo_id': None, 'caller': None, 'use_iterator_for_get_pages': False}
Attempting update/simulation of firewall rules to network L_******************
Traceback (most recent call last):
  File "/user/automation-scripts/import_mx_l3.py", line 123, in <module>
    main(sys.argv[1:])
  File "/user/automation-scripts/import_mx_l3.py", line 109, in main
    m.mx_l3_firewall.updateNetworkL3FirewallRules(net_id, rules=fw_rules, syslogDefaultRule=default_logging)
AttributeError: 'DashboardAPI' object has no attribute 'mx_l3_firewall'

**Comment by mpapazog** [comment]
Posted updated version of import_mx_l3.py. Please test if it fixes your issue
